services:
  - type: web
    name: casafiore
    env: node
    buildCommand: npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 